// <auto-generated />
using MarketOurs.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MarketOurs.Data.Migrations
{
    [DbContext(typeof(MarketContext))]
    [Migration("20260614060612_UpdateParadeDBSearchChinese")]
    partial class UpdateParadeDBSearchChinese
    {
    }
}
